# Generated by Django 3.1.7 on 2021-03-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='viewer', max_length=12),
        ),
    ]
