# Generated by Django 3.1.7 on 2021-03-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
