# Generated by Django 3.1.7 on 2021-03-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='unit',
        ),
    ]
