# Generated by Django 3.1.7 on 2021-03-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_tenant_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='tenant',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.unit'),
        ),
    ]
