# Generated by Django 3.1.7 on 2021-03-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20210322_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('resolved', models.BooleanField()),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.unit')),
            ],
        ),
    ]
