# Generated by Django 3.1.7 on 2021-03-25 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
