# Generated by Django 3.1.7 on 2021-03-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_maintenance_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
