# Generated by Django 3.1.7 on 2021-04-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('uploaded_file', models.FileField(upload_to='management/documents')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.unit')),
            ],
        ),
    ]
